// Realistic Indian tech jobs dataset
const JOBS_DATA = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/intern",
    description: "Join Amazon's internship program to work on real-world projects. You'll collaborate with experienced engineers, learn best practices, and contribute to scalable systems. Perfect for students looking to kickstart their tech career."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Spring Boot", "Angular"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/get",
    description: "TCS Graduate Engineer Trainee program offers comprehensive training in enterprise technologies. Work on client projects, gain exposure to global teams, and build a strong foundation in software development."
  },
  {
    id: 3,
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/careers/junior-backend",
    description: "Build scalable payment infrastructure at Razorpay. Work on APIs that process millions of transactions daily. Learn from senior engineers and contribute to India's leading fintech platform."
  },
  {
    id: 4,
    title: "Frontend Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://careers.swiggy.com/intern",
    description: "Create delightful user experiences for millions of Swiggy users. Work on React components, optimize performance, and learn modern frontend practices in a fast-paced startup environment."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Java", "TestNG"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹18k–₹30k/month Internship",
    applyUrl: "https://zoho.com/careers/qa-intern",
    description: "Ensure quality across Zoho's product suite. Learn automation testing, write test cases, and work closely with development teams. Great opportunity to understand software quality processes."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://flipkartcareers.com/data-analyst-intern",
    description: "Analyze customer behavior and business metrics at Flipkart. Work with large datasets, create visualizations, and provide insights that drive business decisions. Perfect for data enthusiasts."
  },
  {
    id: 7,
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–6 LPA",
    applyUrl: "https://infosys.com/careers/java-dev",
    description: "Develop enterprise applications using Java and Spring framework. Work on client projects, learn industry standards, and grow your career with Infosys's structured learning programs."
  },
  {
    id: 8,
    title: "Python Developer (Fresher)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://wipro.com/careers/python-fresher",
    description: "Build web applications using Python and Django. Work on backend services, API development, and database design. Join Wipro's fresher program with comprehensive training."
  },
  {
    id: 9,
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/careers/react-dev",
    description: "Build user interfaces for India's leading payments app. Work on React components, optimize bundle sizes, and ensure smooth user experiences. Join a high-growth fintech company."
  },
  {
    id: 10,
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C#", ".NET", "Azure", "SQL Server"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://microsoft.com/careers/intern",
    description: "Work on Microsoft's cloud platform and enterprise solutions. Learn from world-class engineers, contribute to Azure services, and build your career at a global tech leader."
  },
  {
    id: 11,
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "JavaScript", "HTML", "CSS"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://accenture.com/careers/get",
    description: "Start your career with Accenture's Graduate Engineer Trainee program. Receive structured training, work on global projects, and develop skills in cutting-edge technologies."
  },
  {
    id: 12,
    title: "Junior Backend Developer",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "GraphQL", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "8–12 LPA",
    applyUrl: "https://cred.club/careers/backend-junior",
    description: "Build backend services for CRED's credit card rewards platform. Work with modern tech stack, learn microservices architecture, and contribute to India's fastest-growing fintech."
  },
  {
    id: 13,
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Vue.js", "JavaScript", "Webpack"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹22k–₹38k/month Internship",
    applyUrl: "https://freshworks.com/careers/frontend-intern",
    description: "Create beautiful interfaces for Freshworks' SaaS products. Work on React components, learn modern frontend tools, and contribute to products used by thousands of businesses."
  },
  {
    id: 14,
    title: "QA Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Appium", "Java", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹20k–₹32k/month Internship",
    applyUrl: "https://paytm.com/careers/qa-intern",
    description: "Ensure quality of Paytm's mobile and web applications. Learn mobile testing, automation tools, and work on India's largest payments platform."
  },
  {
    id: 15,
    title: "Data Analyst Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Pandas", "SQL", "Power BI"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹24k–₹42k/month Internship",
    applyUrl: "https://juspay.in/careers/data-analyst",
    description: "Analyze payment transaction data at Juspay. Work with large datasets, create dashboards, and provide insights to improve payment success rates."
  },
  {
    id: 16,
    title: "Java Developer (0-1)",
    company: "Capgemini",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Microservices", "Docker"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "4–7 LPA",
    applyUrl: "https://capgemini.com/careers/java-dev",
    description: "Develop microservices using Java and Spring Boot. Work on cloud-native applications, learn DevOps practices, and grow with Capgemini's learning ecosystem."
  },
  {
    id: 17,
    title: "Python Developer (Fresher)",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Flask", "MySQL", "Linux"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://cognizant.com/careers/python-fresher",
    description: "Build Python applications for enterprise clients. Learn web development, database design, and work on real-world projects with Cognizant's structured training."
  },
  {
    id: 18,
    title: "React Developer (1-3)",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Next.js", "TypeScript", "CSS Modules"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–20 LPA",
    applyUrl: "https://zomato.com/careers/react-dev",
    description: "Build user interfaces for Zomato's food delivery platform. Work on React applications, optimize performance, and create delightful experiences for millions of users."
  },
  {
    id: 19,
    title: "SDE Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Cloud", "AI/ML", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹28k–₹45k/month Internship",
    applyUrl: "https://ibm.com/careers/intern",
    description: "Work on IBM's cloud and AI platforms. Learn enterprise technologies, contribute to innovative projects, and build your career with a global tech leader."
  },
  {
    id: 20,
    title: "Graduate Engineer Trainee",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Oracle DB", "SQL", "PL/SQL"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "4–6 LPA",
    applyUrl: "https://oracle.com/careers/get",
    description: "Join Oracle's Graduate Engineer Trainee program. Work on database technologies, learn Oracle Cloud, and develop skills in enterprise software development."
  },
  {
    id: 21,
    title: "Junior Backend Developer",
    company: "Meesho",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "7–11 LPA",
    applyUrl: "https://meesho.com/careers/backend-junior",
    description: "Build scalable backend systems for Meesho's e-commerce platform. Work on APIs, learn distributed systems, and contribute to India's leading social commerce startup."
  },
  {
    id: 22,
    title: "Frontend Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "TypeScript", "Tailwind CSS", "Vite"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/careers/frontend-intern",
    description: "Create modern user interfaces for Razorpay's payment products. Work with React and TypeScript, learn component design, and build products used by millions."
  },
  {
    id: 23,
    title: "QA Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Postman", "JavaScript", "Git"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://careers.swiggy.com/qa-intern",
    description: "Ensure quality of Swiggy's food delivery platform. Learn API testing, write test cases, and work with cross-functional teams in a fast-paced environment."
  },
  {
    id: 24,
    title: "Data Analyst Intern",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Google Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "₹26k–₹42k/month Internship",
    applyUrl: "https://phonepe.com/careers/data-analyst-intern",
    description: "Analyze user behavior and transaction data at PhonePe. Create reports, build dashboards, and provide insights to improve product features and user experience."
  },
  {
    id: 25,
    title: "Java Developer (0-1)",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "SAP ABAP", "HANA", "Fiori"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "5–8 LPA",
    applyUrl: "https://sap.com/careers/java-dev",
    description: "Develop enterprise solutions using Java and SAP technologies. Work on SAP Cloud Platform, learn enterprise software development, and grow with SAP's global team."
  },
  {
    id: 26,
    title: "Python Developer (Fresher)",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "3–6 LPA",
    applyUrl: "https://dell.com/careers/python-fresher",
    description: "Build Python applications for Dell's enterprise solutions. Work on web services, learn backend development, and contribute to Dell's digital transformation initiatives."
  },
  {
    id: 27,
    title: "React Developer (1-3)",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Next.js", "TypeScript", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "11–19 LPA",
    applyUrl: "https://cred.club/careers/react-dev",
    description: "Build premium user interfaces for CRED's credit card rewards app. Work on React applications, optimize performance, and create delightful experiences for premium users."
  },
  {
    id: 28,
    title: "SDE Intern",
    company: "Google",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Python", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://google.com/careers/intern",
    description: "Work on Google's products and infrastructure. Learn from world-class engineers, contribute to scalable systems, and build your career at one of the world's leading tech companies."
  },
  {
    id: 29,
    title: "Graduate Engineer Trainee",
    company: "Wipro",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Spring", "MySQL", "JavaScript"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://wipro.com/careers/get",
    description: "Join Wipro's Graduate Engineer Trainee program. Receive comprehensive training, work on client projects, and develop skills in enterprise software development."
  },
  {
    id: 30,
    title: "Junior Backend Developer",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "PostgreSQL", "Celery"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zomato.com/careers/backend-junior",
    description: "Build backend services for Zomato's food delivery platform. Work on APIs, learn microservices architecture, and contribute to India's leading food tech company."
  },
  {
    id: 31,
    title: "Frontend Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹24k–₹38k/month Internship",
    applyUrl: "https://flipkartcareers.com/frontend-intern",
    description: "Create user interfaces for Flipkart's e-commerce platform. Work on React components, optimize performance, and learn modern frontend development practices."
  },
  {
    id: 32,
    title: "QA Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Manual Testing", "Cypress", "JavaScript", "Git"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹22k–₹36k/month Internship",
    applyUrl: "https://razorpay.com/careers/qa-intern",
    description: "Ensure quality of Razorpay's payment products. Learn automation testing, write test cases, and work with development teams to deliver high-quality software."
  },
  {
    id: 33,
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Tableau", "Excel"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹23k–₹40k/month Internship",
    applyUrl: "https://careers.swiggy.com/data-analyst-intern",
    description: "Analyze delivery and customer data at Swiggy. Create visualizations, build dashboards, and provide insights to improve operations and customer experience."
  },
  {
    id: 34,
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Mysore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "4–6 LPA",
    applyUrl: "https://infosys.com/careers/java-dev",
    description: "Develop enterprise applications using Java and Spring Boot. Work on client projects, learn industry best practices, and grow your career with Infosys."
  },
  {
    id: 35,
    title: "Python Developer (Fresher)",
    company: "TCS",
    location: "Kolkata",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Flask", "SQLite", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/python-fresher",
    description: "Build Python applications for TCS clients. Learn web development, work on real projects, and develop skills in Python programming and backend development."
  },
  {
    id: 36,
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux Toolkit", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/careers/react-dev",
    description: "Build user interfaces for PhonePe's payments app. Work on React components, optimize performance, and create smooth user experiences for millions of users."
  },
  {
    id: 37,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "AWS", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹30k–₹48k/month Internship",
    applyUrl: "https://amazon.jobs/intern",
    description: "Work on Amazon's cloud infrastructure and services. Learn AWS technologies, contribute to scalable systems, and build your career at a global tech leader."
  },
  {
    id: 38,
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "HTML", "CSS"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://accenture.com/careers/get",
    description: "Start your career with Accenture's Graduate Engineer Trainee program. Receive structured training, work on global projects, and develop enterprise software skills."
  },
  {
    id: 39,
    title: "Junior Backend Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "7–11 LPA",
    applyUrl: "https://juspay.in/careers/backend-junior",
    description: "Build payment processing systems at Juspay. Work on high-throughput APIs, learn distributed systems, and contribute to India's leading payment gateway."
  },
  {
    id: 40,
    title: "Frontend Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "TypeScript", "Styled Components", "Storybook"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹26k–₹42k/month Internship",
    applyUrl: "https://cred.club/careers/frontend-intern",
    description: "Create premium user interfaces for CRED's credit card rewards platform. Work on React components, learn design systems, and build products for premium users."
  },
  {
    id: 41,
    title: "QA Intern",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Python", "Pytest"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "₹21k–₹34k/month Internship",
    applyUrl: "https://zomato.com/careers/qa-intern",
    description: "Ensure quality of Zomato's food delivery platform. Learn automation testing, write test scripts, and work with development teams to deliver bug-free software."
  },
  {
    id: 42,
    title: "Data Analyst Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "SQL", "Pandas", "Matplotlib"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹24k–₹39k/month Internship",
    applyUrl: "https://meesho.com/careers/data-analyst-intern",
    description: "Analyze e-commerce data at Meesho. Work with large datasets, create visualizations, and provide insights to improve business metrics and user experience."
  },
  {
    id: 43,
    title: "Java Developer (0-1)",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "Oracle DB"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "4–7 LPA",
    applyUrl: "https://capgemini.com/careers/java-dev",
    description: "Develop enterprise applications using Java and Spring framework. Work on client projects, learn industry standards, and grow with Capgemini's learning programs."
  },
  {
    id: 44,
    title: "Python Developer (Fresher)",
    company: "Cognizant",
    location: "Coimbatore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Linux"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://cognizant.com/careers/python-fresher",
    description: "Build Python web applications for Cognizant clients. Learn Django framework, work on backend services, and develop skills in Python programming."
  },
  {
    id: 45,
    title: "React Developer (1-3)",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "11–19 LPA",
    applyUrl: "https://careers.swiggy.com/react-dev",
    description: "Build user interfaces for Swiggy's food delivery platform. Work on React applications, optimize performance, and create delightful experiences for millions of users."
  },
  {
    id: 46,
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C#", ".NET", "Azure", "SQL Server"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹32k–₹50k/month Internship",
    applyUrl: "https://microsoft.com/careers/intern",
    description: "Work on Microsoft's cloud platform and enterprise solutions. Learn Azure technologies, contribute to cloud services, and build your career at Microsoft."
  },
  {
    id: 47,
    title: "Graduate Engineer Trainee",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Oracle DB", "SQL", "PL/SQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "4–6 LPA",
    applyUrl: "https://oracle.com/careers/get",
    description: "Join Oracle's Graduate Engineer Trainee program. Work on database technologies, learn Oracle Cloud, and develop enterprise software development skills."
  },
  {
    id: 48,
    title: "Junior Backend Developer",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://paytm.com/careers/backend-junior",
    description: "Build backend services for Paytm's payments platform. Work on APIs, learn microservices architecture, and contribute to India's leading payments company."
  },
  {
    id: 49,
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Vue.js", "JavaScript", "Webpack"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "₹23k–₹37k/month Internship",
    applyUrl: "https://freshworks.com/careers/frontend-intern",
    description: "Create user interfaces for Freshworks' SaaS products. Work on React and Vue.js components, learn modern frontend tools, and build products for businesses."
  },
  {
    id: 50,
    title: "QA Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Appium", "Java", "TestNG"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "₹22k–₹36k/month Internship",
    applyUrl: "https://flipkartcareers.com/qa-intern",
    description: "Ensure quality of Flipkart's e-commerce platform. Learn mobile and web testing, write test cases, and work with development teams."
  },
  {
    id: 51,
    title: "Data Analyst Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Looker"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹41k/month Internship",
    applyUrl: "https://razorpay.com/careers/data-analyst-intern",
    description: "Analyze payment transaction data at Razorpay. Work with large datasets, create reports, and provide insights to improve payment success rates and user experience."
  },
  {
    id: 52,
    title: "Java Developer (0-1)",
    company: "Wipro",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 10,
    salaryRange: "4–6 LPA",
    applyUrl: "https://wipro.com/careers/java-dev",
    description: "Develop enterprise applications using Java and Spring Boot. Work on client projects, learn microservices, and grow your career with Wipro."
  },
  {
    id: 53,
    title: "Python Developer (Fresher)",
    company: "Infosys",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://infosys.com/careers/python-fresher",
    description: "Build Python web applications for Infosys clients. Learn Django framework, work on backend services, and develop skills in Python programming."
  },
  {
    id: 54,
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/careers/react-dev",
    description: "Build user interfaces for PhonePe's payments app. Work on React components, optimize bundle sizes, and create smooth user experiences."
  },
  {
    id: 55,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "AWS", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹28k–₹45k/month Internship",
    applyUrl: "https://amazon.jobs/intern",
    description: "Work on Amazon's cloud infrastructure and services. Learn AWS technologies, contribute to scalable systems, and build your career at Amazon."
  },
  {
    id: 56,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Spring", "MySQL", "JavaScript"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/get",
    description: "Join TCS's Graduate Engineer Trainee program. Receive comprehensive training, work on client projects, and develop enterprise software skills."
  },
  {
    id: 57,
    title: "Junior Backend Developer",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "GraphQL", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "8–12 LPA",
    applyUrl: "https://cred.club/careers/backend-junior",
    description: "Build backend services for CRED's credit card rewards platform. Work on GraphQL APIs, learn microservices, and contribute to India's premium fintech."
  },
  {
    id: 58,
    title: "Frontend Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹24k–₹38k/month Internship",
    applyUrl: "https://careers.swiggy.com/frontend-intern",
    description: "Create user interfaces for Swiggy's food delivery platform. Work on React components, optimize performance, and learn modern frontend development."
  },
  {
    id: 59,
    title: "QA Intern",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Java", "TestNG"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹21k–₹35k/month Internship",
    applyUrl: "https://zomato.com/careers/qa-intern",
    description: "Ensure quality of Zomato's food delivery platform. Learn automation testing, write test scripts, and work with development teams."
  },
  {
    id: 60,
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Tableau", "Excel"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://flipkartcareers.com/data-analyst-intern",
    description: "Analyze customer behavior and business metrics at Flipkart. Work with large datasets, create visualizations, and provide insights to drive business decisions."
  }
];
